---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: debian
    dockerfile: ../common/Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - create
    - converge
    - verify
    - idempotence
    - destroy
verifier:
  name: ansible
