---
- name: USERAPPS | Oracle JDK | Prerequisites
  import_tasks: prerequisites.yml

- name: USERAPPS | Oracle JDK | Set Download URL
  set_fact:
    pv_ua_jdk_download_url: "{{  vars[ 'pv_ua_jdk_download_url_' + ansible_facts.architecture + '_' +  pv_ua_jdk_version|string  ]  }}"

- name: USERAPPS | Oracle JDK | Create install directory
  ansible.builtin.file:
    path: "{{  pv_ua_jdk_install_path  }}"
    state: directory

- name: USERAPPS | Oracle JDK | Get downloaded file stat
  stat:
    path: "{{  pv_ua_jdk_tarball_download_path  }}"
  register: pv_ua_jdk_downloaded_file_stat

- name: USERAPPS | Oracle JDK | Newly Downloaded
  when: not pv_ua_jdk_downloaded_file_stat.stat.exists
  block:
    - name: USERAPPS | Oracle JDK | Download tarball
      ansible.builtin.get_url:
        url: "{{  pv_ua_jdk_download_url  }}"
        dest: "{{  pv_ua_jdk_tarball_download_path  }}"

    - name: USERAPPS | Oracle JDK | Unarchive the tarball
      ansible.builtin.unarchive:
        src: "{{  pv_ua_jdk_tarball_download_path  }}"
        dest: "{{  pv_ua_jdk_install_path  }}"
        extra_opts: [--strip-components=1]
        remote_src: true
