---
- name: Development Workspace Applications | Install Java Packages
  package:
    name: "{{  rv_server_ws_apps_def_java_packages  }}"
    state: present

- name: Development Workspace Applications | Adding Java init scripts
  template:
    src: "init-profilescripts.sh.{{  ansible_os_family  }}.j2"
    dest: /etc/profile.d/nebula-java-auto.sh
    mode: "0644"
