---
- name: Development Workspace Applications | Prerequisite
  include_tasks: 0000-pre-install-checks.yml
  tags:
    - always
  args:
    apply:
      tags:
        - always

- name: Development Workspace Applications | Include Vars for {{  ansible_os_family  }}
  include_vars: "{{  ansible_os_family  }}.yml"
  tags:
    - always

- name: Development Workspace Applications | Install Essentials
  include_tasks: essentials.yml
  args:
    apply:
      tags:
        - always
  tags:
    - always

- name: Development Workspace Applications | Install Java
  include_tasks: java.yml
  args:
    apply:
      tags:
        - java
        - never
  tags:
    - always

- name: Development Workspace Applications | Set user bin path and GPG tty
  blockinfile:
    path: /etc/profile.d/10-nebula-sw-init-auto.sh
    create: yes
    mode: "0755"
    marker: "# {mark} ANSIBLE MANAGED BLOCK :: Added by nebula server workspace setup"
    block: |
      export PATH=$HOME/.local/bin:$PATH:/usr/sbin
      export GPG_TTY=$(tty)
      export EDITOR=vim
  tags:
    - always
