---
- name: USERAPPS | NodeJS | Prerequisites
  import_tasks: prerequisites.yml

- name: USERAPPS | NodeJS | Set Download URL x86_64
  set_fact:
    pv_ua_nodejs_download_url: "{{  vars[ 'pv_ua_nodejs_download_url_' + ansible_facts.architecture + '_' +  pv_ua_nodejs_version|string  ]  }}"

- name: USERAPPS | NodeJS | Create install directory
  ansible.builtin.file:
    path: "{{  pv_ua_nodejs_install_path  }}"
    state: directory

- name: USERAPPS | NodeJS | Get downloaded file stat
  stat:
    path: "{{  pv_ua_nodejs_tarball_download_path  }}"
  register: pv_ua_nodejs_downloaded_file_stat

- name: USERAPPS | NodeJS | New Download
  when: not pv_ua_nodejs_downloaded_file_stat.stat.exists
  block:
    - name: USERAPPS | NodeJS | Download tarball
      ansible.builtin.get_url:
        url: "{{  pv_ua_nodejs_download_url  }}"
        dest: "{{  pv_ua_nodejs_tarball_download_path  }}"

    - name: USERAPPS | NodeJS | Unarchive the tarball
      ansible.builtin.unarchive:
        src: "{{  pv_ua_nodejs_tarball_download_path  }}"
        dest: "{{  pv_ua_nodejs_install_path  }}"
        extra_opts: [--strip-components=1]
        remote_src: true
