FROM "{{ item.image }}"

USER root

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt upgrade -y && apt-get install -y python3-pip git

RUN useradd -m -s /bin/bash -d /home/molecule-user molecule-user

USER molecule-user
