---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include arpanrec.server_workspace"
      include_role:
        name: "arpanrec.server_workspace"
        tasks_from: dotfiles
