---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: debian
    dockerfile: Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
