---
- name: USERAPPS | Golang | Molecule | Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include GO"
      include_role:
        name: "arpanrec.server_workspace"
        tasks_from: go
