name: Molecule Test on merge requests
on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    working-directory: 'arpanrec.server_workspace'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: 'arpanrec.server_workspace'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test dotfiles
      run: |
        molecule test -s dotfiles

    - name: Test utils-scripts
      run: |
        molecule test -s utils-scripts

    - name: Test Java
      run: |
        molecule test -s java

    - name: Test nodejs
      run: |
        molecule test -s nodejs

    - name: Test GO
      run: |
        molecule test -s go
